### ISSUE TITLE
letsencrypt is not compatible with python-openssl v0.14

### ISSUE THREAD

**Issue by erebus2** [letsencrypt/letsencrypt#885]
Moving this here from https://github.com/letsencrypt/letsencrypt-debian/issues/6

When I try to build letsencrypt on Debian, I get the following error:

    ERROR: test_csr_no_sans (acme.crypto_util_test.PyOpenSSLCertOrReqSANTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/directory/letsencrypt-debian-master/acme/acme/crypto_util_test.py", line 88, in test_csr_no_sans
        self.assertEqual(self._call_csr('csr-nosans.pem'), [])
      File "/directory/letsencrypt-debian-master/acme/acme/crypto_util_test.py", line 78, in _call_csr
        return self._call(test_util.load_csr, name)
      File "/directory/letsencrypt-debian-master/acme/acme/crypto_util_test.py", line 72, in _call
        return _pyopenssl_cert_or_req_san(loader(name))
      File "/directory/letsencrypt-debian-master/acme/acme/crypto_util.py", line 141, in _pyopenssl_cert_or_req_san
        for i in range(cert_or_req.get_extension_count())]
      File "/directory/letsencrypt-debian-master/acme/acme/jose/util.py", line 44, in __getattr__
        return getattr(self._wrapped, name)
    AttributeError: 'X509Req' object has no attribute 'get_extension_count'

It seems to me that the cause of this issue is in file acme/acme/crypto_util.py, lines 137 to 141:

    if hasattr(cert_or_req, 'get_extensions'):  # X509Req
            extensions = cert_or_req.get_extensions()
        else:  # X509
            extensions = [cert_or_req.get_extension(i)
                          for i in range(cert_or_req.get_extension_count())]

This means that an X509Req object is supposed to have a get_extensions() method while an X509 object is supposed to have two methods called get_extension() and get_extension_count().

However, as far as I can tell, an X509Req object is not supposed to provide any of the aforementioned methods. This means that the if-condition fails on X509Req objects (which doesn't seem to be what we want) and get_extension_count() is called on the X509Req object which causes the compiler error.

Gotcha: The missing get_extensions() method was added in python-openssl v0.15 which is not in Debian Stable (jessie).

Is there a way to make this work with python-openssl v0.14? [or maybe even earlier?]

If the answer is no, we would have to require v0.15 of python-openssl as a build-dependency in debian/control.

**Comment by kuba** [comment]
Unfortunately, this is a **WONTFIX**.

In fact, we rely on `PyOpenSSL>=0.15`, see https://github.com/letsencrypt/letsencrypt/blob/74b2e3bc515b5f7e805883a26f1b0e47ed686098/acme/setup.py#L15. Over the time we are very likely to require even higher versions. `debian/control` already marks this dependency: https://github.com/letsencrypt/letsencrypt-debian/blob/9a4d934ce143dad00f92bfa4eacc9b23e6f9426a/debian/control#L51.

For the time being you can try to run our `virtualenv` setup as described at http://letsencrypt.readthedocs.org/en/latest/using.html#installation.

**Comment by erebus2** [comment]
Thank you very much for pointing this out.

I actually missed that the debian package already has a run-time dependency on python-openssl v0.15. However, in order to fix building, python-openssl v0.15 would need to be required at compile-time.
